### ISSUE TITLE
邮箱用户手册整理.xlsx

### ISSUE THREAD

**Issue by zsjvtm** [Just-silent/ggdy#1]
请问一下这个文件在哪里下载？

**Comment by Just-silent** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不好意思，这个涉及到公司的机密了，这个还不方便
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月16日 ***@***.***> 写道： 




请问一下这个文件在哪里下载？

**Comment by zsjvtm** [comment]
能否给个结构参考一下？



***@***.***
 
发件人： Silent
发送时间： 2022-05-16 16:15
收件人： Just-silent/ggdy
抄送： zsjvtm; Author
主题： Re: [Just-silent/ggdy] 邮箱用户手册整理.xlsx (Issue #1)






font{ 
line-height: 1.6; 
} 
ul,ol{ 
padding-left: 20px; 
list-style-position: inside; 
} 



不好意思，这个涉及到公司的机密了，这个还不方便









***@***.***




在2022年5月16日 ***@***.***> 写道： 




请问一下这个文件在哪里下载？

**Comment by Just-silent** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    样例见附件，大致如该目录，多少个域可能有偏差。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月16日 ***@***.***> 写道： 




能否给个结构参考一下？















***@***.***



 



发件人： Silent



发送时间： 2022-05-16 16:15



收件人： Just-silent/ggdy



抄送： zsjvtm; Author



主题： Re: [Just-silent/ggdy] 邮箱用户手册整理.xlsx (Issue #1)



























font{ 



line-height: 1.6; 



} 



ul,ol{ 



padding-left: 20px; 



list-style-position: inside; 



} 















不好意思，这个涉及到公司的机密了，这个还不方便







































***@***.***



















在2022年5月16日 ***@***.***> 写道： 



















请问一下这个文件在哪里下载？

**Comment by Just-silent** [comment]
样例见附件，大致如该目录，多少个域可能有偏差
[用户手册样例.xlsx](https://github.com/Just-silent/ggdy/files/8708701/default.xlsx)
。
