### ISSUE TITLE
数据集方便提供一下吗？

### ISSUE THREAD

**Issue by liujiang123456** [Just-silent/ggdy#2]
作者的代码非常nice，我想借鉴一下你的数据集可以吗？我的邮箱：1391932906@qq.com

**Comment by Just-silent** [comment]
你加下我的QQ吧，我晚点发你QQ：1563723284
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年7月23日 22:12
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [Just-silent/ggdy] 数据集方便提供一下吗？ (Issue #2)
        
      
    
  

***@***.***

**Comment by Aurora15kk** [comment]
> 你加下我的QQ吧，我晚点发你QQ：1563723284 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年7月23日 22:12 收件人 ***@***.***> 抄送人 ***@***.***> 主题 [Just-silent/ggdy] 数据集方便提供一下吗？ (Issue #2) ***@***.*** —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

您好，我也想借鉴一下数据集，已经加您qq了，还望可以通过

**Comment by Just-silent** [comment]
https://github.com/Just-silent/ggdy/issues/1
